ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: "stackclass-issuer"
  hosts:
    - host: git.stackclass.dev
      paths:
        - path: /
  tls:
   - secretName: "stackclass-gitea-tls"
     hosts:
       - git.stackclass.dev
gitea:
  admin:
    username: "<REPLACE_WITH_GIT_SERVER_USERNAME>"
    password: <REPLACE_WITH_GIT_SERVER_PASSWORD>
    email: "<REPLACE_WITH_GIT_SERVER_EMAIL>"
    passwordMode: initialOnlyNoReset

valkey-cluster:
  enabled: false

valkey:
  enabled: true
  global:
    valkey:
      password: "<REPLACE_WITH_VALKEY_PASSWORD>"

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        database: gitea
        username: gitea
        password: "<REPLACE_WITH_GITEA_DB_PASSWORD>"
