apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: basic
  targetNamespace: tekton-pipelines
  pipeline:
    enable-api-fields: "stable"
    performance:
      replicas: 1
      threads-per-controller: 2
  chain:
    disabled: true
  result:
    disabled: true
  pruner:
    disabled: false
    schedule: "0 3 * * *"
    startingDeadlineSeconds: 100
    resources:
      - taskrun
      - pipelinerun
    keep: 3
    prune-per-resource: true
