frontend:
  ingress:
    enabled: true
    host: stackclass.dev
    tls:
      enabled: true
  secrets:
    analyticsId: "<REPLACE_WITH_ANALYTICS_ID>"
    githubClientId: "<REPLACE_WITH_GITHUB_CLIENT_ID>"
    githubClientSecret: "<REPLACE_WITH_GITHUB_CLIENT_SECRET>"

backend:
  ingress:
    host: api.stackclass.dev
    tls:
      enabled: true
  secrets:
    gitServerEndpoint: "https://git.stackclass.dev"
    gitServerUsername: "<REPLACE_WITH_GIT_SERVER_USERNAME>"
    gitServerPassword: "<REPLACE_WITH_GIT_SERVER_PASSWORD>"
    dockerRegistryEndpoint: "docker.stackclass.dev"
    authSecret: "<REPLACE_WITH_AUTH_SECRET>"

postgresql:
  enabled: true
  auth:
    username: stackclass
    database: stackclass
    password: "<REPLACE_WITH_SC_DB_USERNAME>"

issuer:
  enabled: true
  email: "<REPLACE_WITH_ISSUER_EMAIL>"
  environment: "prod"
