frontend:
  ingress:
    enabled: true
    host: stackclass.dev
    tls:
      enabled: true
  secrets:
    analyticsId: ""
    githubClientId: "<REPLACE_WITH_GITHUB_CLIENT_ID>"
    githubClientSecret: "<REPLACE_WITH_GITHUB_CLIENT_SECRET>"

backend:
  ingress:
    host: api.stackclass.dev
    tls:
      enabled: true
  secrets:
    gitServerEndpoint: "https://git.stackclass.dev"
    gitServerUsername: "<REPLACE_WITH_GIT_SERVER_USERNAME>"
    gitServerPassword: "<REPLACE_WITH_GIT_SERVER_PASSWORD>"
    dockerRegistryEndpoint: "docker.stackclass.dev"

issuer:
  enabled: true
  email: "hello@stackclass.dev"
  environment: "prod"
